# mkdocs.yml
site_name: Ticket engine Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Intro: index.md
  - Explanation: explanation.md
  - reference.md
  - limitations.md
  - tutorials.md
