# mkdocs.yml
site_name: Calculation Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Intro: index.md
  - Logic explanation: explanation.md
  - tutorials.md
  - how-to-guides.md
  - reference.md